Fix #1473
tempesta-tech/tempesta pull request #1555
Opened 2022-02-02 10:26 UTC by dmpetroff

Fixed `ss_getpeername` so it uses source IP and port now.

`TfwClient` is cached across multiple connections and its `addr` field contains address with port from the first encounter of that client. This means that if we use said address for printing, port part will eventually get outdated. This is why we disabling client port printing from `tfw_http_cli_error_resp_and_log()`.

2022-02-02 14:08 UTC, krizhanovsky requested changes
Need to review other usages of similar macros printing client port.

2022-02-02 14:08 UTC, krizhanovsky commented on fw/http.c
> +		T_WARN_ADDR(msg, &req->conn->peer->addr, TFW_NO_PORT);
That's not the only place of printing with the client port, e.g. we also have similar printing in the warning at `tfw_http_req_fwd_send()`. There are also other macros with similar logic, e.g. `T_WARN_ADDR_STATUS()`. All the places must be reviewed whether it makes sense to print the port (e.g. there is an error message when we can't open listening port - we definitely need port in the message) and fix all the places.

2022-02-03 11:20 UTC, dmpetroff commented
Carefully looked through code for `TFW_WITH_PORT` and replaced it to `TFW_WITHOUT_PORT` where appropriate.

Finding out how to run tests to make sure that changes haven't broke anything else.

2022-02-03 20:11 UTC, krizhanovsky approved these changes
LGTM

2022-02-04 12:02 UTC, merged