Add runtime check for not present adx, may be false negative
tempesta-tech/tempesta pull request #1556
Opened 2022-02-02 14:32 UTC by ttaym

There are some cloud providers that do support adx instructions in their VPS but do not show this support in /proc/cpuinfo.

I suppose there is need for runtime check of supporting theas instruct if their support not present in /proc/cpuinfo by running binary that contain adcx instruction for example emmited by inline asm.

2022-02-02 15:13 UTC, krizhanovsky requested changes
Basically good to be merged after several improvements

2022-02-02 15:13 UTC, krizhanovsky commented on check/Makefile
> +	find . \( -name \*.exe -exec rm -f {} \; \)
we don't have exe's

2022-02-02 15:13 UTC, krizhanovsky commented on Makefile
> +	ADX_TEST_BIN = $(DIR)check/adx_test.exe
```suggestion
	ADX_TEST_BIN = $(DIR)check/adx_test
```

2022-02-02 15:13 UTC, krizhanovsky commented on Makefile
> +	ADX_SUPPORTED := $(shell $(ADX_TEST_BIN) | if grep -q "ADX supported"; then echo -n "y"; fi)
We already have `scripts/check_conf.pl` for this purpose, so I'd suggest to move the compilation into the script. We also can embed `adx_test.c` code right into the script and compile it in `/tmp` with a generated file name and remove it after the check.

The Makefile can run the `scripts/check_conf.pl` to make sure that configuration is good.

2022-02-03 08:03 UTC, ttaym commented
@krizhanovsky 
I have made all requested changes and resolve all discusstions.

2022-02-03 19:59 UTC, krizhanovsky approved these changes
LGTM after minor cleanups.

2022-02-03 19:59 UTC, krizhanovsky commented on Makefile
> +	ADX_SUPPORTED := $(shell $(CHECK_CONF) 2>/dev/null | grep ADX | if grep -q ': found'; then echo y; fi)
Too wide lines, we keep lines in 80 characters long https://github.com/tempesta-tech/tempesta/blob/master/CodingStyle

2022-02-03 19:59 UTC, krizhanovsky commented on scripts/check_conf.pl
> +    print "'Intel ADX Instruction Extensions' support: ", index($test_output, "ADX supported") == -1 || $exit_status != 0 ? "NOT " : "", "found\n";
Also too wide line. And please update the copyright year for the file to 2022.

2022-02-04 08:49 UTC, merged