#1697 Fix header field name length check
tempesta-tech/tempesta pull request #1721
Opened 2022-10-13 10:23 UTC by avbelov23

https://github.com/tempesta-tech/tempesta/issues/1697

In checking the length of the header field name, we take into account the processed unfixed characters (__FSM_MATCH_MOVE) and fixed, and not just parsed at the current iteration of the state

2022-10-15 14:04 UTC, krizhanovsky requested changes
Need to rework the fix, add fix for HTTP/2 and tests for both the HTTP/1 and HTTP/2

2022-10-15 14:04 UTC, krizhanovsky commented on fw/http_parser.c
> +		}							\
We need `n` only to not to get into the `if` statement at the below, so the `else` branch is senseless and this `if` condition can be aggregated with the below one. Moreover, we don't need `n` value, just need to for 0 or not, i.e. this means "whether we saw at least one character in the header?". The last thing is that we really can use `parser` and don't need `&msg->stream->parser.hdr`. I propose to rewrite the fix as
```C
--- a/fw/http_parser.c
+++ b/fw/http_parser.c
@@ -1252,10 +1252,11 @@ __FSM_STATE(RGen_HdrOtherN) {                                           \
                /*                                                      \
                 * Header name must contain at least one character, but \
                 * ':' can be found at the beginning of a new skb or    \
-                * fragment, it's ok.                                   \
+                * fragment, it's ok. We also might get into the state  \
+                * either on the fist character of the header or not.   \
                */                                                      \
-               if (unlikely(!__fsm_sz                                  \
-                            && TFW_STR_EMPTY(&msg->stream->parser.hdr))) \
+               if (unlikely(!__fsm_sz && TFW_STR_EMPTY(parser->hdr)    \
+                            && p != (unsigned char *)parser->hdr.data))\
                {                                                       \
                        TFW_PARSER_BLOCK(RGen_HdrOtherN);               \
                }                                                 
```

2022-10-18 21:29 UTC, krizhanovsky approved these changes
LGTM, just please make the small cleanup

2022-10-18 21:29 UTC, krizhanovsky commented on fw/http_parser.c
> +                            && p == (unsigned char *)parser->hdr.data))\
Seems misaligned `&&` and trailing slash

2022-10-19 13:34 UTC, s0nx approved these changes
LGTM

2022-10-19 18:04 UTC, merged