Do not forward connection-specific headers to/from H1 backend for H2 clients
tempesta-tech/tempesta pull request #1885
Opened 2023-05-25 12:14 UTC by dmpetroff

For problem description see #1805
Implementation:
- for incoming connection headers I've changed parser to behave like it does for `Connection` header
- for connection headers coming from upstream, I'm setting `TFW_STR_HBH_HDR` header during parse phase

Related PR for tempesta-test is here: https://github.com/tempesta-tech/tempesta-test/pull/462
All that tests are passing locally

2023-06-01 18:31 UTC, krizhanovsky approved these changes
LGTM with the couple of adjustments

2023-06-01 18:31 UTC, krizhanovsky commented on fw/http_parser.c
> +			__FSM_H2_OTHER_n(4);
Could you please add a comment with reference to RFC 9113 8.2.2 that we tread an HTTP/2 message having `Upgrade` header as malformed? The same for the `Proxy-Connection` above

2023-06-01 18:31 UTC, krizhanovsky commented on fw/http_parser.c
> +					&& C8_INT7_LCM(p + 11, 'n', 't', 'i', 'c', 'a', 't', 'e', ':'))
Please adjust the too wide lines here and above - we fit 80, maybe 85 if necessary, characters in line

2023-06-02 10:07 UTC, const-t requested changes
Current PR is good for me. But would be better to add the last connection-specific header `TE` to this PR. Tests for this header implemented in [RP 461 malformed](https://github.com/tempesta-tech/tempesta-test/pull/461)

2023-06-05 12:42 UTC, krizhanovsky requested changes
Unit tests are required

2023-06-05 12:42 UTC, krizhanovsky commented on fw/http_parser.c
> +			     TFW_HTTP_HDR_RAW, 1);
Please add unit tests for the new parsing logic to `fw/t/unit/test_http2_parser.c`

2023-06-05 13:12 UTC, const-t requested changes

2023-06-08 19:02 UTC, krizhanovsky approved these changes
LGTM. Couple of reviews ago I added a request to add a comment referencing the RFC, which was not addressed, so I just pushed the commit on my own. Please address **all** review comments in future (either comment them if you disagree or just fix).

2023-06-09 10:35 UTC, const-t approved these changes
LGTM

2023-06-10 09:32 UTC, merged