Rework allocation for stream schedulers.
tempesta-tech/tempesta pull request #2160
Opened 2024-07-03 11:39 UTC by EvgeniiMekhanik

According to our discussion the best way is to allocate two pages for each connection and save streams schedulers after the end of `struct TfwH2Conn`. When we create new stream, we get scheduler for such stream from the list of preallocated schedulers. If limit of such schedulers is exceeded we allocate new page and use it to initialize new schedulers.

2024-07-04 13:39 UTC, EvgeniiMekhanik commented
I think about add space for the whole TfwStream structure at the end of http2 context but it has 912B size, so we need to much memory for this purpose.

2024-07-08 11:41 UTC, const-t requested changes

2024-07-08 11:41 UTC, const-t commented on fw/http2.c
> +	pg = alloc_pages(GFP_ATOMIC, 1);
Is this not too much just for H2 context?

I've a doubts about page allocation at this place. I would prefer to use `TfwPool` or memcache.

2024-07-08 11:41 UTC, const-t commented on fw/http_stream_sched.h
> +	struct list_head		in_empty_list;
Could we get rid off `in_empty_list` if we will store the pointer to the next entry in the current entry? I mean that while `TfwStreamSchedEntry` in the freelist it casted to `void *` that points to the next `TfwStreamSchedEntry` when we remove it from the list, we zeroes the pointer and cast to `TfwStreamSched` again. In other words when `TfwStreamSchedEntry` in empty list it's casted to linked list.

2024-07-16 09:56 UTC, closed without merging