Implementation multi pattern regular expressions
tempesta-tech/tempesta pull request #2161
Opened 2024-07-05 14:07 UTC by biathlon3

2024-07-05 14:45 UTC, biathlon3 commented
For deployment see file install.txt. Description will be expanded.

2024-07-08 05:54 UTC, biathlon3 commented
This PR works on Kernel 6.8.9

Description of using hscollider - http://intel.github.io/hyperscan/dev-reference/tools.html

Description of regular expression syntax - https://perldoc.perl.org/perlre
It is supported in Hyperscan not fully, constraints described here - http://intel.github.io/hyperscan/dev-reference/compilation.html

Now regex implemented in tempasta config as fallows: 
for locations, added keyword "regex" and regex started with "^";
for httptables, regex started with "^".

for example:
```
location regex "^/new/" {
    frang_limits {
	http_body_len 5;
	http_strict_host_checking true;
    }
}

http_chain {
  uri == "^/html/" -> default;
  -> default;
}
```

2024-07-26 13:29 UTC, biathlon3 commented
I squashed it into one commit so it can be reviewed.

2026-01-08 13:50 UTC, const-t commented
Description of using hscollider - http://intel.github.io/hyperscan/dev-reference/tools.html

Description of regular expression syntax - https://perldoc.perl.org/perlre
It is supported in Hyperscan not fully, constraints described here - http://intel.github.io/hyperscan/dev-reference/compilation.html

Use `~` for regexp in location and http chain:
```
location ~ "/^/show/id/[0-9]+/i" {
    frang_limits {
	http_body_len 5;
	http_strict_host_checking true;
    }
}

http_chain {
  uri ~  "^/html/" -> default;
  -> default;
}
```

2026-01-30 14:10 UTC, EvgeniiMekhanik commented
I catch memory leak in case when configuraion fails

kmemleak_alloc+0x4a/0x90
    __kmalloc_noprof+0x3a5/0x520
    tfw_kzalloc+0x14/0x20 [tempesta_lib]
    rex_make_item+0x27/0x100 [xdp_rex]
    configfs_mkdir+0x735/0xd30
    vfs_mkdir+0x45c/0x7a0
    do_mkdirat+0x292/0x320
    __x64_sys_mkdir+0xd7/0x130
    x64_sys_call+0x10cf/0x25f0
    do_syscall_64+0x7e/0x170
    entry_SYSCALL_64_after_hwframe+0x76/0x7e

config:

listen 80;
listen 443 proto=h2;
        
tls_certificate /home/evgeny/workdir/certs/tempesta-tech.test.crt;
tls_certificate_key /home/evgeny/workdir/certs/tempesta-tech.test.key;
tls_match_any_server_name;

access_log off;

srv_group grp1 {
    server 127.0.0.1:8000;
}

vhost test {
    proxy_pass grp1;
    location ~ "/^/article/id/[0-9]+/" {
        proxy_pass grp1;
    }
    location ~ "/shop/" {
        proxy_pass grp1;
    }
    location ~ "/wiki/" {
        proxy_pass grp1;
    }
}

vhost work {
    proxy_pass grp1;
    location ~ "/shop/i" {
        proxy_pass grp1;
    }
    location ~ "/wiki/" {
        proxy_pass grp1;
    }
}

http_chain {
    host ~ "/test/i" -> test;
    host ~ "/work/i" -> work;
    host ~ "/(a+)+$$/" -> work;
    -> block;
}

2026-01-30 14:11 UTC, EvgeniiMekhanik commented on fw/vhost.c
> +        { "regex",	TFW_HTTP_MATCH_O_REGEX },
broken aligment

2026-01-30 14:11 UTC, EvgeniiMekhanik commented on fw/vhost.c
> +        [TFW_HTTP_MATCH_O_REGEX]	= __tfw_match_regex,
broken alignment

2026-01-30 16:27 UTC, EvgeniiMekhanik commented on regex/Makefile
> +CC_FLAGS_HSRUNTIME	+= -DHAVE_AVX512
We should check that AVX512 is present. I catch BUG when I compile it with this flag, but without real avx512 support

2026-02-02 09:03 UTC, EvgeniiMekhanik commented on scripts/tempesta.sh
>  		elif [[ $line =~ '!include' ]]; then
I think that also it's better to use `pattern='^!include[[:space:]]+[^[:space:]]+'`
and then
elif [[ $line =~ $pattern' ]]; then

to skip patterns like ~inlcudeqqqq

2026-02-02 09:58 UTC, EvgeniiMekhanik commented on fw/vhost.c
> +		r = tfw_write_regex(arg, &regex_idx);
Please look comment in `tfw_write_regex`. It seems that comment before `if (len < sizeof(number_of_regex))` is incorrect. Because here we pass `arg`, not `argmem` here

2026-02-02 17:06 UTC, EvgeniiMekhanik requested changes

2026-02-02 17:06 UTC, EvgeniiMekhanik commented on fw/http_match.c
> +	if (wc_arg && regex) {
host ~ "*" -> test -> block still work here, because raw_hdr_name is NULL, is it ok?

2026-02-02 17:06 UTC, EvgeniiMekhanik commented on Makefile
> +install:
I am not sure, that it is a good idea. We don't install tempesta_fw.conf to etc directory for example. I think it's better to pass path to this script using bash variable. And by default i think it's better to set default value in ./scripts folder

2026-02-02 17:06 UTC, EvgeniiMekhanik commented on scripts/regex_setup.sh
> +regex_dir_path=${REGEX_DIR_PATH:="/opt/tempesta/regex"}
It seems that you set `regex_dir_path` in regex.c without any chance to change it.

2026-02-02 17:06 UTC, EvgeniiMekhanik commented on fw/regex.c
> +	ret = call_usermodehelper("/bin/bash", argv, envp, UMH_WAIT_PROC);
Why it is better then call this script after Tempesta FW will be load? I am not sure that it is better then call it directly from tempesta.sh

2026-02-02 17:06 UTC, EvgeniiMekhanik commented on fw/http_match.c
> +find_spaces(const char *s, size_t len, size_t *begin_spaces_out,
strange return values for this function. For string like `ddddddd` :
begin_spaces_out == 0 and
end_spaces_out == 0

2026-02-02 17:06 UTC, EvgeniiMekhanik commented on regex/kmod/rex.c
> +EXPORT_SYMBOL(bpf_scan_bytes);
This function never used in our code. We're just returning the code here to its original state, like in the repository we got it from, right?

2026-02-02 17:06 UTC, EvgeniiMekhanik commented on fw/http_msg.h
> +#define S_COLON			":"
Can you explain please the changes with S_COLON and find spaces. How it worked before and why we change this behavior?

2026-02-02 17:06 UTC, EvgeniiMekhanik commented on fw/http_match.c
> +		full_name_len = name_len + SLEN(S_COLON);
Why `full_name_len` is not initialized for TFW_HTTP_MATCH_F_COOKIE

2026-02-02 17:21 UTC, EvgeniiMekhanik commented
I catch kasan BUG in
`tests.http_rules.test_http_tables.TestHttpTablesEmptyHdrPattern.test_empty_name`. Please run all tests with kasan and kmemleak and check results.

2026-02-03 10:00 UTC, EvgeniiMekhanik commented
I also can't understand
if I add
hdr cookie ~ "/fff*/" -> block; in http_chain should request with  ("cookie", "fffoooo=bbb"), blocked?

2026-02-03 15:57 UTC, const-t commented
> I also can't understand if I add hdr cookie ~ "/fff*/" -> block; in http_chain should request with ("cookie", "fffoooo=bbb"), blocked?

Works well, [the test](https://github.com/tempesta-tech/tempesta-test/pull/910/changes/11ceb0c3bc73d4ab09d4d7e3bde0c54b25cb3b5b). Probably another rule was matched before cookie.

2026-02-03 17:10 UTC, const-t commented on fw/http_match.c
> +		full_name_len = name_len + SLEN(S_COLON);
I'm not sure, but I think it is legacy code. This condition `field != TFW_HTTP_MATCH_F_COOKIE` actually always true, cookie is special header.

2026-02-03 17:13 UTC, const-t commented on fw/http_match.c
> +	if (wc_arg && regex) {
No, it is not ok. Such regex also not allowed for special headers. Fixed

2026-02-03 17:14 UTC, const-t commented on fw/vhost.c
> +		r = tfw_write_regex(arg, &regex_idx);
Fixed comment and changed condition

2026-02-04 13:03 UTC, const-t commented on fw/http_match.c
> +find_spaces(const char *s, size_t len, size_t *begin_spaces_out,
This is correct, but I've changed arguments name and added comment.

2026-02-10 13:31 UTC, const-t commented on fw/http_match.c
> +		full_name_len = name_len + SLEN(S_COLON);
I read it carefully and this condition is the part of the code that do matching using `cookie "name" == "value"` where name and value are parameters of cookie. In this case `raw_hdr_name` contains cookie parameter name instead of header name.

2026-02-10 14:10 UTC, const-t commented on regex/Makefile
> +CC_FLAGS_HSRUNTIME	+= -DHAVE_AVX512
I've added the check

2026-02-10 14:10 UTC, const-t commented on scripts/tempesta.sh
>  		elif [[ $line =~ '!include' ]]; then
fixed

2026-02-10 14:11 UTC, const-t commented on Makefile
> +install:
Agreed, install target isn't good. Now I pass it via module parameter.

2026-02-10 14:12 UTC, const-t commented on scripts/regex_setup.sh
> +regex_dir_path=${REGEX_DIR_PATH:="/opt/tempesta/regex"}
REGEX_DIR_PATH is env var, tempesta.sh passes it to kernel and then kernel sets is when calls helper

2026-02-10 14:19 UTC, const-t commented on fw/regex.c
> +	ret = call_usermodehelper("/bin/bash", argv, envp, UMH_WAIT_PROC);
When we calling `setup_script.sh` from tempesta.sh we do this only when all modules loaded and Tempesta ready to receive connection, but there is interval between tempesta is ready and regex is compiled. If Tempesta receives a request during this interval, we can’t apply the regex because it hasn’t been compiled yet.

2026-02-10 14:19 UTC, const-t commented on regex/kmod/rex.c
> +EXPORT_SYMBOL(bpf_scan_bytes);
Yes, you are right

2026-02-10 14:24 UTC, const-t commented on fw/http_msg.h
> +#define S_COLON			":"
Previously we stored a patter for header match with space after colon, after the patch we save the pattern without spaces. We do that to not skip spaces in pattern during header comparison, especially for http2, where spaces are forbidden.

2026-02-10 14:26 UTC, const-t commented
> I catch kasan BUG in
> `tests.http_rules.test_http_tables.TestHttpTablesEmptyHdrPattern.test_empty_name`. Please run all tests with kasan and kmemleak and check results.

Fixed

2026-02-19 09:34 UTC, EvgeniiMekhanik commented on scripts/tempesta.sh
> +		elif [[ $line =~ ^[[:space:]]*!include[[:space:]]+.+$ ]]; then
Is it ok that we can have any count of space before include?

2026-02-19 09:44 UTC, EvgeniiMekhanik commented on fw/t/unit/regex.c
> +../../regex.c
No empty line at the end of the file?

2026-02-19 10:49 UTC, EvgeniiMekhanik approved these changes
Please also add three stress tests with reconfiguration with regexp:
- With success reconfiguration regexp config - regexp config
- Fail reconfig
- Success was regexp now not regexp

2026-04-09 18:32 UTC, krizhanovsky approved these changes
A few improvements are possible, but looks good to merge in general.

I appreciate `match_hdr_raw()` refactoring!

2026-04-09 18:32 UTC, krizhanovsky commented on fw/http_match.c
> +		[TFW_HTTP_MATCH_O_REGEX]	= TFW_STR_EQ_REGEX
Please add some info to the HTTP tables wiki, make good examples

2026-04-09 18:32 UTC, krizhanovsky commented on fw/http_tbl.c
Add `~` and `~*` to the operation description

2026-04-09 18:32 UTC, krizhanovsky commented on fw/http_match.c
> +		return ERR_PTR(-EINVAL);
```suggestion
		T_ERR_NL("http_match: use simple wildcard argument `hdr == *`"
		         " instead of regex.\n");
```
By the way

2026-04-09 18:32 UTC, krizhanovsky commented on fw/vhost.c
> + * location.
Please add regular expressions for `location` to wiki

2026-04-09 18:32 UTC, krizhanovsky commented on regex/kmod/rex.c
Please add our copyrights to all changed files like regex/kmod/rex.c

2026-04-09 18:32 UTC, krizhanovsky commented on fw/t/unit/test_http_match.c
>  	TEST_RUN(http_match, choose_host);
Could you please add unit tests for regular expressions

2026-04-09 18:32 UTC, krizhanovsky commented on install.txt
> +git checkout ag_Multi-pattern-regular-expressions
I think this should be README.md in the `regex` directory and reference the original https://github.com/G-Core/linux-regex-module to give credits to the team. Probably this wiki https://github.com/tempesta-tech/tempesta/wiki/Installation-tempesta-supported-regex should be in the README - it's useful for us, but not for users (can we remove the wiki page after that?)

2026-04-09 18:32 UTC, krizhanovsky commented on scripts/tempesta.sh
> +rgx_mod=xdp_rex
That project was for the XDP module and technically could be useful in https://github.com/tempesta-tech/xFWas , but anyway the regexps, especially for Tempesta FW, have nothing to do about XDP. Let's rename the module to something like `tempesta_regex` that an administrator can easily see all our modules

2026-04-09 18:32 UTC, krizhanovsky commented on fw/http_match.c
> +	sprintf(file_name, "/opt/tempesta/regex/%u.txt", number_of_db_regex);
We should get the path from the script: this path is likely to change, IIRC @symstu recently made a change in Escudo that all the products are installed in `/opt/tempesta` and have their own subdirs, `fw`, `xfw`, `webshield`. We can do this with sysctl or module parameter, but this should be a generic home/work directory specification

2026-04-09 18:32 UTC, krizhanovsky commented on regex/kmod/rex.c
> +int rex_scan_tfwstr(const TfwStr *str, struct rex_scan_attr *attr)
Now the code is in our tree, so please adjust coding style of all new and changed functions and definitions

2026-04-09 18:32 UTC, krizhanovsky commented on regex/kmod/rex.c
> -int bpf_scan_vector(const char *const *buf,
I think there is no reason to remove the BPF-purpose routines - they might be useful in xFW, but for sure we don't need code for old kernel versions

2026-04-09 18:32 UTC, krizhanovsky commented on fw/regex.c
> +static char *regex_setup_script_path = "/lib/tempesta/scripts/regex_setup.sh";
This path is also installation-dependent, we should get it from the outside: sysctl, module param etc

2026-04-09 18:32 UTC, krizhanovsky commented on fw/http_match.c
> +}
Isn't it the same as `tfw_cstricmp_2lc()`?

2026-05-04 13:18 UTC, const-t commented on fw/http_match.c
> +}
The main difference is `tfw_cstricmp_2lc()` always calls `tolower()` for both arguments `string` and `pattern` but `__cmp_hdr_raw_name()` doesn't call `tolower()` for h2 at all and do `memcpy_fast()`. For h1 `tolower()` will be called only for `string` not for a substring.

2026-05-04 15:02 UTC, const-t commented on regex/kmod/rex.c
> -int bpf_scan_vector(const char *const *buf,
I removed this this function because it has been added by us in this commit https://github.com/tempesta-tech/tempesta/pull/2161/changes/4d5e3d48d0d74d0f7cef00b4c6d9febe96d05865 and this code is not test covered and even not being used, I believe this is bad approach to leave the code which we are not sure about.

2026-05-11 13:59 UTC, const-t commented on fw/regex.c
> +static char *regex_setup_script_path = "/lib/tempesta/scripts/regex_setup.sh";
Maybe you commented old version, currently this path is passed to module using parameters.

2026-05-11 14:00 UTC, const-t commented on fw/http_match.c
> +	sprintf(file_name, "/opt/tempesta/regex/%u.txt", number_of_db_regex);
Maybe you commented old version, currently this path is passed to module using parameters.

2026-05-11 14:01 UTC, const-t commented on fw/vhost.c
> + * location.
I've added. https://github.com/tempesta-tech/tempesta/wiki/Virtual-hosts-and-locations

2026-05-11 14:01 UTC, const-t commented on fw/http_tbl.c
added

2026-05-11 14:02 UTC, const-t commented on fw/http_match.c
> +		[TFW_HTTP_MATCH_O_REGEX]	= TFW_STR_EQ_REGEX
added https://github.com/tempesta-tech/tempesta/wiki/HTTP-tables

2026-05-11 14:04 UTC, const-t commented
@krizhanovsky PR is updated. Please consider all review comments addressed.

2026-05-16 08:33 UTC, merged